# Visit https://github.com/lowlighter/metrics/blob/master/action.yml for full reference
name: Metrics
on:
  # Schedule updates (each hour)
  schedule: [{ cron: "0 * * * *" }]
  # Lines below let you run workflow manually and on each commit
  workflow_dispatch:
  push: { branches: ["master", "main"] }
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          filename: base.svg
          base: header, community, repositories
          config_timezone: Europe/Berlin
          plugin_habits: yes
          plugin_habits_from: 200 # Use 200 events to compute habits
          plugin_habits_days: 14 # Keep only events from last 14 days
          plugin_habits_facts: yes # Display facts section
          plugin_habits_trim: yes # Trim unused hours on daily chart
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          filename: commits.svg
          base: ""
          plugin_isocalendar: yes
          plugin_pagespeed_token: ${{ secrets.PAGESPEED_TOKEN }} # Optional but recommended
          plugin_pagespeed: yes
          plugin_pagespeed_detailed: no # Print detailed audit metrics
          plugin_pagespeed_screenshot: no # Display a screenshot of your website
          plugin_pagespeed_url: gcampes.me # Website to audit (defaults to your GitHub linked website)
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          filename: achievements.svg
          base: ""
          plugin_achievements: yes
          plugin_achievements_threshold: B # Display achievements with rank B or higher
          plugin_achievements_secrets: yes # Display unlocked secrets achievements
          plugin_achievements_ignored: octonaut # Hide octonaut achievement
          plugin_achievements_limit: 0
          plugin_achievements_display: compact
